# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

#Trigger blocks can't contain variables or template expressions.

#Push trigger
# A push trigger specifies which branches cause a continuous integration build to run.
#- main
#- develop
# If you specify no push trigger, pushes to any branch trigger a build.
#trigger: none # will disable CI builds (but not PR builds)

trigger:
- master

#specifies which pool to use for a job of the pipeline
pool:
  vmImage: ubuntu-latest
#pool:
  #name: My_name
  #vmImage: windows-latest
  #agent.name -equals 'agent.name'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
# JUnit is an open source framework, which is used for writing and running tests.
# Provides annotations to identify test methods.
# Provides assertions for testing expected results.
# Provides test runners for running tests.
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
